### ISSUE TITLE
first event being created before wkst?

### ISSUE THREAD

**Issue by jam33** [jkbrzt/rrule#72]
Unfortunately, I'm not an iCal/rrule expert, so this might be my interpretation being wrong, however, if I set the wkst value to be a day that is after today, I would assume that no events could take place today as part of this rule?

For instance, if today is friday, and i have a weekly rule that repeats on mon/tues/wed/thur/fri and I set the wkst to "SA", shouldn't the first event be monday of next week and NOT today (since friday is before saturday)?

I've attached a screenshot to help explain my question.

Thanks for an amazing script!

**Comment by toxaq** [comment]
wkst doesn't mean when your rule starts, it's setting what classifies as the start of your week. Javascript by default uses sun-sat. Most Western countries use mon-sun (hence the term week-end) however some countries don't do this. Leave the wkst as RRule.MO as the default and use dtstart to set the first date of occurrences.

**Comment by gabimoncha** [comment]
leaving this here for posterity, since I also struggled a bit to understand why on earth `wkst` is needed

taken from the [RFC 5545](https://www.rfc-editor.org/rfc/rfc5545.html) standard itself

> An example where the days generated makes a difference because of WKST:
> 
> DTSTART;TZID=America/New_York:19970805T090000
> RRULE:FREQ=WEEKLY;INTERVAL=2;COUNT=4;BYDAY=TU,SU;WKST=MO
> 
> ==> (1997 EDT) August 5,10,19,24
> 
> changing only WKST from MO to SU, yields different results...
> 
> DTSTART;TZID=America/New_York:19970805T090000
> RRULE:FREQ=WEEKLY;INTERVAL=2;COUNT=4;BYDAY=TU,SU;WKST=SU
> 
> ==> (1997 EDT) August 5,17,19,31

<img width="242" alt="Image" src="https://github.com/user-attachments/assets/a056c147-7e21-42fe-98a5-a225ec9b956f" />


since this reads to `every 2 weeks on Tuesday, Sunday for 4 times` you get two cases:
- when week starts on Monday you get, the first week 5,10 and the next other week 19, 24
- but when the week starts on Sunday, the first week only holds the 5th. The next other week is 17, 19. And because the count hasn't started, you will also get a third week on 31st
